name: Build SM8150 HyperOS Kernel
on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Kernel Source
        uses: actions/checkout@v4
        with:
          path: kernel

      - name: Install Build Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y git flex bison gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libssl-dev libelf-dev make zip wget tar

      # AOSP官方稳定clang，链接永久有效
      - name: Download AOSP Clang Toolchain
        run: |
          rm -rf clang
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-14.0.0_r48/clang-r498229.tar.gz -O clang.tar.gz
          mkdir clang
          tar -xf clang.tar.gz -C clang --strip-components=1

      - name: Compile Kernel Image
        run: |
          export ARCH=arm64
          export PATH=$PWD/clang/bin:$PATH
          cd kernel
          make clean && make mrproper
          make oneplus_defconfig
          make -j$(nproc)
